### ISSUE TITLE
Improve error messages in YamlParser

### ISSUE THREAD

**Issue by AntoxaBarin** [Cloud-Storage-Team/algnet#160]
Example:

topology.yaml:
```yaml
...
link:
  from: sender
  to: receiver
  latency: 1ns
  throughput: Gbps  # Error: no value
...
```

Error message:
```bash
[15:29:04] [ERROR] [main.cpp:21] Error: stoul
```
