### ISSUE TITLE
BUG: handle segfault in YamlParser

### ISSUE THREAD

**Issue by AntoxaBarin** [Cloud-Storage-Team/algnet#219]
Topology config `topology.yml` : 

```yaml
devices:  # NO SENDER!
  receiver1:
    type: receiver
  bus:
    type: switch

links:
  link1:
    from: sender1
    to: bus
    latency: 10ns
    throughput: 10Gbps
    ingress_buffer_size: 65536B
    egress_buffer_size: 65536B
  link2:
    from: bus
    to: sender1
    latency: 10ns
    throughput: 10Gbps
    ingress_buffer_size: 65536B
    egress_buffer_size: 65536B
  link5:
    from: receiver1
    to: bus
    latency: 10ns
    throughput: 10Gbps
    ingress_buffer_size: 65536B
    egress_buffer_size: 65536B 
  link6:
    from: bus
    to: receiver1
    latency: 10ns
    throughput: 10Gbps
    ingress_buffer_size: 65536B
    egress_buffer_size: 65536B    
```

Simulation config `simulation.yml`:

```yaml
topology_config_path: topology.yml

flows:
  flow1:
    sender_id: "sender1"
    receiver_id: "receiver1"
    packet_size: 1024
    packet_interval: 100
    number_of_packets: 1000

algorithm: basic
simulation_time: 100000
```

```console
foo@bar:~$ ./simulator simulation.yml
Segmentation fault (core dumped)
```
