### ISSUE TITLE
Update clang-format config

### ISSUE THREAD

**Issue by AntoxaBarin** [Cloud-Storage-Team/algnet#229]
Current `.clang-format` config allows several possible code formattings. 

Example:

```cpp
        for (auto [dest_device, links] : routing_table) {
            for (auto [link, paths_count] : links) {
                src_device->update_routing_table(dest_device, link,
                                                 paths_count);
```  

```cpp
        for (auto [dest_device_id, links] : routing_table) {
            for (auto [link, paths_count]: links) {
                src_device->update_routing_table(dest_device_id, link, paths_count);
```

These two examples will pass CI clang-format check. We want change `.clang-format` to get the only one right formatting.

Possible `.clang-format`:

```yaml
BasedOnStyle: Google
DerivePointerAlignment: false
IncludeBlocks: Preserve
AttributeMacros: ["noexcept"]
IndentRequires: false
ColumnLimit: 120
IndentWidth: 4
TabWidth: 4
AccessModifierOffset: -4
BinPackParameters: false
BinPackArguments: false
AllowAllParametersOfDeclarationOnNextLine: false
AlignAfterOpenBracket: BlockIndent
AlwaysBreakAfterDefinitionReturnType: None
PenaltyReturnTypeOnItsOwnLine: 200
```
